name: company_1

services:
  company_1:
    container_name: company_1
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    image: company_1:latest
    ports:
      - "8090:8080"
    environment:
      APP_NAME: "SS Gujarat Logistics Services"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: "base64:kgk/4DW1vEVy7aEvet5FPp5un6PIGe/so8H0mvoUtW0="
      APP_URL: "https://ssgls.in"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/storage/app/database.sqlite
      CACHE_STORE: file
      SESSION_DRIVER: file
      SESSION_LIFETIME: "240"
      SESSION_DOMAIN: "ssgls.in"
      SANCTUM_STATEFUL_DOMAINS: "ssgls.in"
      SESSION_SECURE_COOKIE: "true"
      TRUSTED_PROXIES: "*"
      DOMPDF_ENABLE_REMOTE: "false"
      OFFICIAL_DOCUMENT_ARCHIVE_PATH: "/official-documents"
      GEMINI_API_KEY: "AQ.Ab8RN6KijH6JvqvgfjKI_D5_mq3L01luU3DM-Pk_mr58JDR7ZQ"
    volumes:
      - D:/SSGLS_DATABASE/database.sqlite:/var/www/html/storage/app/database.sqlite
      - D:/Backup_Data:/var/www/html/Backup_Data
      - ./storage/app/public:/var/www/html/storage/app/public
      - ./storage/app/templates:/var/www/html/storage/app/templates
      - C:/DONOTTOUCH/IMPDOCUMENT:/official-documents
    restart: unless-stopped
