name: my-company

services:
  my-company:
    container_name: my-company
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    image: my-company:latest
    ports:
      - "8090:8080"
    environment:
      APP_NAME: "My Company"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: "base64:kgk/4DW1vEVy7aEvet5FPp5un6PIGe/so8H0mvoUtW0="
      APP_URL: "http://localhost:8090"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/storage/app/database.sqlite
      CACHE_STORE: file
      SESSION_DRIVER: file
      SESSION_LIFETIME: "240"
      SESSION_DOMAIN: "localhost"
      SANCTUM_STATEFUL_DOMAINS: "127.0.0.1:8090,localhost:8090"
      TRUSTED_PROXIES: "*"
      DOMPDF_ENABLE_REMOTE: "false"
      OFFICIAL_DOCUMENT_ARCHIVE_PATH: "/official-documents"
    volumes:
      - ./database/database.sqlite:/var/www/html/storage/app/database.sqlite
      - ./storage/app/public:/var/www/html/storage/app/public
      - ./storage/app/templates:/var/www/html/storage/app/templates
      - C:/DONOTTOUCH/IMPDOCUMENT:/official-documents
    restart: unless-stopped
